name: Skill/content issue
description: Report incorrect behavior, unclear instructions, or metadata/doc issues.
title: "[Issue]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue.
        This repository contains AI skills and markdown/YAML content.
  - type: textarea
    id: problem
    attributes:
      label: What is wrong?
      description: Describe the issue in one or two sentences.
      placeholder: The skill instructions are unclear/inaccurate for this use case.
    validations:
      required: true
  - type: input
    id: affected_path
    attributes:
      label: Affected path
      description: Skill or file path where the issue exists.
      placeholder: skills/<skill-name>/SKILL.md
    validations:
      required: true
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue type
      options:
        - Skill behavior/output quality
        - Instructions are unclear or conflicting
        - Metadata/config issue (agents/openai.yaml)
        - Broken links or references
        - Repository docs/workflow issue
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction details
      description: Include the prompt/input and steps used to reproduce.
      placeholder: |
        Prompt/input:
        Steps:
        1. ...
        2. ...
      render: markdown
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: Relevant runtime/context details if applicable.
      placeholder: |
        - OS:
        - Agent runtime:
        - Additional context:
  - type: textarea
    id: proposed_fix
    attributes:
      label: Proposed fix (optional)
      description: If you have an idea for a fix, describe it here.
      render: markdown
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and did not find a duplicate.
          required: true
        - label: This is not a security vulnerability report (see SECURITY.md).
          required: true
