name: Bug report
description: Report a reproducible problem in this repository.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is going wrong?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a minimal sequence of steps.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details.
      placeholder: |
        - OS:
        - Shell:
        - Node version:
        - Make version:
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or output
      description: Paste error output, stack traces, or lint output if available.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and did not find a duplicate.
          required: true
        - label: I can reproduce this issue on the latest version of the repository.
          required: true

