name: Feature request
description: Suggest an improvement for this repository or its skill workflows.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: A clear and concise description of the pain point.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change you want to see.
      placeholder: What should be added or changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternatives did you evaluate?
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: How would this improve contributor or user experience?
  - type: textarea
    id: scope
    attributes:
      label: Scope and files
      description: Mention expected files/directories impacted.
      placeholder: e.g., skills/<skill-name>/..., Makefile, docs, CI workflow
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and did not find a duplicate.
          required: true
        - label: This request is not related to a security vulnerability (see SECURITY.md).
          required: true

