name: Skill/repo enhancement
description: Propose a new skill or improvements to existing skill/workflow content.
title: "[Request]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement.
        Use this for skill additions, skill updates, and repository workflow/docs enhancements.
  - type: dropdown
    id: request_type
    attributes:
      label: Request type
      options:
        - New skill proposal
        - Existing skill enhancement
        - Repository docs/workflow enhancement
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case/problem
      description: What user need or contributor pain point does this solve?
      placeholder: Describe the scenario and why current skills/docs are not enough.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
      placeholder: Outline the skill content, metadata changes, or workflow changes.
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: How do we know this request is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: input
    id: impacted_paths
    attributes:
      label: Expected impacted path(s)
      description: Skill/file paths likely to be updated.
      placeholder: skills/<skill-name>/..., README.md, CONTRIBUTING.md
  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Related issues, examples, or external references.
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and did not find a duplicate.
          required: true
        - label: This request is not related to a security vulnerability (see SECURITY.md).
          required: true
