name: Skill misbehavior report
description: Report unexpected or incorrect behavior from a skill or repository instructions.
title: "[Misbehavior]: "
labels:
  - misbehavior
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a misbehavior.
        This repository contains AI skills and markdown/YAML content.
  - type: input
    id: affected_path
    attributes:
      label: Affected skill/file path
      description: Path where this misbehavior is rooted.
      placeholder: skills/<skill-name>/SKILL.md
    validations:
      required: true
  - type: textarea
    id: prompt_input
    attributes:
      label: Prompt/input used
      description: Include the prompt or input that triggered this behavior.
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: misbehavior_type
    attributes:
      label: Misbehavior type
      options:
        - Skill behavior/output is incorrect
        - Instructions are unclear or conflicting
        - Metadata/config issue (agents/openai.yaml)
        - Broken links or references
        - Repository docs/workflow issue
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: Observed behavior
      description: What happened?
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Provide minimal steps to reproduce this misbehavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: markdown
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: Relevant runtime/context details if applicable.
      placeholder: |
        - OS:
        - Agent runtime:
        - Additional context:
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and did not find a duplicate.
          required: true
        - label: This is not a security vulnerability report (see SECURITY.md).
          required: true
